chhs-apqd-elasticsearch:
  container_name: chhs-apqd-elasticsearch
  restart: unless-stopped
  image: elasticsearch:1.5.2 
  ports:
    - "9200:9200"
    - "9300:9300"

chhs-apqd-postgresql:
  container_name: chhs-apqd-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  environment:
    - POSTGRES_USER=chhs-apqd    
	- POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
