msap-prototype-prod-elasticsearch:
  container_name: msap-prototype-prod-elasticsearch
  restart: unless-stopped
  image: elasticsearch:1.5.2
  # volumes:
  #   - ~/volumes/jhipster/msap-prototype/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200"
    - "9300"
  environment:
    - ES_JAVA_OPTS= -Des.cluster.name=msap-prototype
    - TZ=America/New_York

msap-prototype-prod-postgresql:
  container_name: msap-prototype-prod-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/msap-prototype/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=msap-prototype
    - POSTGRES_PASSWORD=
    - TZ=America/New_York
  ports:
    - "5432"

msap-prototype-prod:
  container_name: msap-prototype-prod
  restart: unless-stopped
  image: kaver79/msap-prototype
  environment:
    - COOKIE=SRV insert indirect nocache
    - TZ=America/New_York
#   - logback_graylogHost=LOGBACK_GRAYLOGHOST
    - SPRING_MAIL_HOST=127.0.0.1
    - SPRING_DATA_ELASTICSEARCH_CLUSTER-NAME=msap-prototype
  ports:
    - "8080"
  links:
    - "msap-prototype-prod-postgresql:POSTGRESQL"
    - "msap-prototype-prod-elasticsearch:ELASTIC"
