msap-prototype-dev-elasticsearch:
  container_name: msap-prototype-dev-elasticsearch
  restart: unless-stopped
  image: elasticsearch:1.5.2
  # volumes:
  #   - ~/volumes/jhipster/msap-prototype/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - ES_JAVA_OPTS= -Des.cluster.name=msap-prototype-dev
    - ES_HEAP_SIZE=3g
    - TZ=America/New_York

msap-prototype-dev-postgresql:
  container_name: msap-prototype-dev-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/msap-prototype/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=msap-prototype
    - POSTGRES_PASSWORD=
    - TZ=America/New_York

  ports:
    - "5432:5432"

msap-prototype-dev:
  container_name: msap-prototype-dev
  restart: unless-stopped
  image: kaver79/msap-prototype
  environment:
    - COOKIE=SRV insert indirect nocache
    - TZ=America/New_York
    - logback_graylogHost=elk-int.msap.engagepoint.com
    - SPRING_MAIL_HOST=mail-int.msap.engagepoint.com
    - SPRING_DATA_ELASTICSEARCH_CLUSTER-NAME=msap-prototype-dev
    - jhipster_metrics_zabbix_enabled=true
    - jhipster_metrics_zabbix_host=zabbix.msap.engagepoint.com
    - jhipster_metrics_zabbix_periodSec=300
    - jhipster_metrics_zabbix_hostMetadata=msap-prototype-dev
  ports:
    - "3080:8080"
  links:
    - "msap-prototype-dev-postgresql:POSTGRESQL"
    - "msap-prototype-dev-elasticsearch:ELASTIC"
