msap-prototype-qa-elasticsearch:
  container_name: msap-prototype-qa-elasticsearch
  restart: unless-stopped
  image: elasticsearch:1.5.2
  # volumes:
  #   - ~/volumes/jhipster/msap-prototype/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200"
    - "9300"
  environment:
    - ES_JAVA_OPTS= -Des.cluster.name=msap-prototype-qa
    - TZ=America/New_York

msap-prototype-qa-postgresql:
  container_name: msap-prototype-qa-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/msap-prototype/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=msap-prototype
    - POSTGRES_PASSWORD=
    - TZ=America/New_York
  ports:
    - "5432"

msap-prototype-qa:
  container_name: msap-prototype-qa
  restart: unless-stopped
  image: kaver79/msap-prototype
  environment:
    - COOKIE=SRV insert indirect nocache
    - TZ=America/New_York
#   - logback_graylogHost=LOGBACK_GRAYLOGHOST
    - SPRING_MAIL_HOST=172.24.232.25
    - SPRING_data_elasticsearch_cluster-name=msap-prototype-qa
  ports:
    - "4080:8080"
  links:
    - "msap-prototype-qa-postgresql:POSTGRESQL"
    - "msap-prototype-qa-elasticsearch:ELASTIC"
