msap-prototype-full-elasticsearch:
  container_name: msap-prototype-full-elasticsearch
  restart: unless-stopped
  image: elasticsearch:1.5.2
  # volumes:
  #   - ~/volumes/jhipster/msap-prototype/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - ES_JAVA_OPTS= -Des.cluster.name=msap-prototype
    - TZ=America/New_York

msap-prototype-full-postgresql:
  container_name: msap-prototype-full-postgresql
  restart: unless-stopped
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/msap-prototype/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=msap-prototype
    - POSTGRES_PASSWORD=
    - TZ=America/New_York
  ports:
    - "5432:5432"

msap-prototype-full:
  container_name: msap-prototype-full
  restart: unless-stopped
  image: kaver79/msap-prototype
  environment:
    - TZ=America/New_York
    - SPRING_DATA_ELASTICSEARCH_CLUSTER-NAME=msap-prototype
#   - SPRING_MAIL_HOST=<YOU_MAIL_RELAY>
#   - logback_graylogHost=<LOGBACK_GRAYLOGHOST>
#   - jhipster_metrics_zabbix_enabled=true
#   - jhipster_metrics_zabbix_host=zabbix.msap.engagepoint.com
#   - jhipster_metrics_zabbix_periodSec=300
#   - jhipster_metrics_zabbix_hostMetadata=msap-prototype-ha	
  ports:
    - "8080:8080"
  links:
    - "msap-prototype-full-postgresql:POSTGRESQL"
    - "msap-prototype-full-elasticsearch:ELASTIC"
